config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'welcome#index'
  resources :categories, only: [:index, :show]
  resources :badges, only: [:index, :show]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/badge.rb
class Badge < ActiveRecord::Base
  belongs_to :category
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  validates :name, presence: true
  validates :description, presence: true
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :badges
  
  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/concerns/badges_controller.rb
class BadgesController < ApplicationController

  def index
    @badges = Badge.all
  end

  def show
    @badge = Badge.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/badges/_badge.html.haml
.row
  .col-md-4
    = image_tag badge.picture.url(:medium)
  .col-md-8
    %h1= badge.name
    %p= badge.description

app/views/badges/index.html.haml
%h1 Badges
= render partial: "badge", collection: @badges

app/views/badges/show.html.haml
.row
  .col-md-4
    = image_tag @badge.picture.url(:medium)
  .col-md-8
    %h1= @badge.name
    %p= @badge.description
    

app/views/categories/_category.html.haml
%h3= category.name
%p= category.description

app/views/categories/index.html.haml
%h1 Categories
= render partial: "category", collection: @categories

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Badges 
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      .navbar-inner
        .container
          %nav
            %ul.nav.navbar-nav.navbar-right
              %li= link_to 'Categories', categories_path
              %li= link_to 'Badges', badges_path
              - if user_signed_in?
                %li= link_to 'Edit profile', edit_user_registration_path
                %li= link_to "Logout", destroy_user_session_path, method: :delete
              - else
                %li= link_to "Sign up", new_user_registration_path
                %li= link_to "Login", new_user_session_path
    .container
      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-danger= alert
      = yield

app/views/welcome/index.html.haml
.center.hero-unit
  %h1 Welcome to the Badges App!
  %h2 This is the home page for my training application about badges.

  = link_to 'Sign up now!', new_user_registration_path, class: 'btn btn-large btn-primary'